# SPDX-License-Identifier: GPL-2.0-only

ifeq ($(SYNC_FENCE_ROOT),)
SYNC_FENCE_ROOT := $(srctree)/techpack/mm
endif

KDIR := $(TOP)/kernel_platform/msm-kernel
include $(SYNC_FENCE_ROOT)/config/kalamammdrivers.conf
LINUXINCLUDE += -include $(SYNC_FENCE_ROOT)/config/kalamammdriversconf.h \
		-I$(SYNC_FENCE_ROOT)/sync_fence/include/

obj-$(CONFIG_QCOM_SPEC_SYNC) += sync_fence.o

sync_fence-y := src/qcom_sync_file.o

EXTRA_CFLAGS += -Wformat-extra-args -Wstrict-prototypes -Wformat-insufficient-args \
		-Wformat-invalid-specifier -Wformat-zero-length -Wnonnull
