# SPDX-License-Identifier: GPL-2.0-only

ifeq ($(MSM_EXT_DISPLAY_ROOT),)
MSM_EXT_DISPLAY_ROOT := $(srctree)/techpack/mm
endif

include $(MSM_EXT_DISPLAY_ROOT)/config/kalamammdrivers.conf
LINUXINCLUDE += -include $(MSM_EXT_DISPLAY_ROOT)/config/kalamammdriversconf.h \
		-I$(MSM_EXT_DISPLAY_ROOT)/msm_ext_display/include/

obj-$(CONFIG_MSM_EXT_DISPLAY) += msm_ext_display.o

msm_ext_display-y := src/msm_ext_display.o

EXTRA_CFLAGS += -Wformat-extra-args -Wstrict-prototypes -Wformat-insufficient-args \
		-Wformat-invalid-specifier -Wformat-zero-length -Wnonnull
